// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 The Koryph Developers

package metrics

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"text/tabwriter"
	"time"

	"github.com/koryph/koryph/internal/fsx"
	"github.com/koryph/koryph/internal/ledger"
	"github.com/koryph/koryph/internal/paths"
	"github.com/koryph/koryph/internal/registry"
)

// TokenComposition is the four-class token breakdown for one entity plus
// derived totals and cache-hit ratio.
type TokenComposition struct {
	// Fresh input tokens (not served from cache).
	Input int64 `json:"input"`
	// Output tokens generated by the model.
	Output int64 `json:"output"`
	// Tokens served from the prompt cache (discounted reads).
	CacheRead int64 `json:"cache_read"`
	// Tokens written into the prompt cache (cache-write cost).
	CacheCreation int64 `json:"cache_creation"`
	// Total = Input + Output + CacheRead + CacheCreation.
	Total int64 `json:"total"`
	// CacheHitRatio = CacheRead / (CacheRead + Input); 0 when both are zero.
	CacheHitRatio float64 `json:"cache_hit_ratio"`
}

func makeComposition(input, output, cacheRead, cacheCreation int64) TokenComposition {
	total := input + output + cacheRead + cacheCreation
	ratio := float64(0)
	if cacheRead+input > 0 {
		ratio = float64(cacheRead) / float64(cacheRead+input)
	}
	return TokenComposition{
		Input:         input,
		Output:        output,
		CacheRead:     cacheRead,
		CacheCreation: cacheCreation,
		Total:         total,
		CacheHitRatio: ratio,
	}
}

// BeadTokenRow is the per-bead token breakdown.
type BeadTokenRow struct {
	// BeadID is the bead tracker ID (may be empty for markdown-plan beads).
	BeadID string `json:"bead_id,omitempty"`
	// PhaseID is the ledger phase identifier.
	PhaseID string `json:"phase_id"`
	// Tier is the model tier used (the Slot.Model value).
	Tier        string           `json:"tier"`
	Composition TokenComposition `json:"composition"`
}

// TierTokenStat is the per-model-tier aggregate.
type TierTokenStat struct {
	Tier        string           `json:"tier"`
	Slots       int              `json:"slots"`
	Composition TokenComposition `json:"composition"`
	// MeanPerSlot is the mean total tokens across slots in this tier.
	MeanPerSlot int64 `json:"mean_per_slot"`
}

// RunTokenSummary is a single run's per-bead token summary, used for the
// tokens-per-bead trend.
type RunTokenSummary struct {
	RunID       string `json:"run_id"`
	StartedAt   string `json:"started_at"`
	Beads       int    `json:"beads"`
	TotalTokens int64  `json:"total_tokens"`
	// MeanPerBead is TotalTokens/Beads; 0 when Beads==0.
	MeanPerBead int64 `json:"mean_per_bead"`
}

// ProjectTokenStat is the per-project token rollup.
type ProjectTokenStat struct {
	ProjectID   string           `json:"project_id"`
	Account     string           `json:"account"`
	Composition TokenComposition `json:"composition"`
	// TotalBeads is the number of distinct bead slots (by phase_id) seen across
	// all runs.
	TotalBeads int `json:"total_beads"`
	// MeanPerBead is the mean total tokens per bead.
	MeanPerBead int64 `json:"mean_per_bead"`
	// ByTier is per-model-tier breakdown, keyed by tier name.
	ByTier map[string]TierTokenStat `json:"by_tier"`
	// Beads is the per-bead list, sorted by total tokens descending.
	Beads []BeadTokenRow `json:"beads"`
	// RunTrend is the tokens-per-bead trend (oldest-first, up to 20 runs).
	RunTrend []RunTokenSummary `json:"run_trend"`
}

// TokenReport is the overall result returned by CollectTokens.
type TokenReport struct {
	GeneratedAt string             `json:"generated_at"`
	Projects    []ProjectTokenStat `json:"projects"`
}

// CollectTokens rolls up per-bead and per-tier token composition from run
// ledgers across managed projects. projectID "" aggregates every registered
// project.
func CollectTokens(store *registry.Store, projectID string) (*TokenReport, error) {
	recs, err := store.List()
	if err != nil {
		return nil, err
	}
	rep := &TokenReport{GeneratedAt: time.Now().UTC().Format(time.RFC3339)}
	for _, rec := range recs {
		if projectID != "" && rec.ProjectID != projectID {
			continue
		}
		stat := collectProjectTokens(rec)
		rep.Projects = append(rep.Projects, stat)
	}
	return rep, nil
}

// collectProjectTokens aggregates token fields for one project's runs.
func collectProjectTokens(rec *registry.Record) ProjectTokenStat {
	stat := ProjectTokenStat{
		ProjectID: rec.ProjectID,
		Account:   rec.AccountProfile,
		ByTier:    map[string]TierTokenStat{},
	}

	// beadAgg accumulates token totals per phase_id across requeues/runs.
	type beadAgg struct {
		beadID string
		tier   string
		in     int64
		out    int64
		cr     int64
		cc     int64
	}
	beads := map[string]*beadAgg{}

	koryphRoot := paths.KoryphRoot(rec.Root)
	entries, err := os.ReadDir(koryphRoot)
	if err != nil {
		return stat
	}

	// Collect run IDs in chronological (oldest-first) order for the trend.
	var runIDs []string
	seen := map[string]bool{}
	for _, e := range entries {
		if e.Type()&os.ModeSymlink != 0 || !e.IsDir() {
			continue
		}
		ledgerPath := filepath.Join(koryphRoot, e.Name(), "ledger.json")
		resolved := ledgerPath
		if r, rerr := filepath.EvalSymlinks(ledgerPath); rerr == nil {
			resolved = r
		}
		if seen[resolved] {
			continue
		}
		seen[resolved] = true
		if fsx.Exists(ledgerPath) {
			runIDs = append(runIDs, e.Name())
		}
	}
	sort.Strings(runIDs) // lexical = chronological (timestamp-prefixed IDs)

	for _, runID := range runIDs {
		ledgerPath := filepath.Join(koryphRoot, runID, "ledger.json")
		var run ledger.Run
		if err := fsx.ReadJSON(ledgerPath, &run); err != nil {
			continue
		}

		var runTotalTokens int64
		runBeadCount := 0

		for _, sl := range run.Slots {
			if sl == nil {
				continue
			}
			// Only aggregate slots that have any token data.
			hasTokens := sl.InputTokens != 0 || sl.OutputTokens != 0 ||
				sl.CacheReadTokens != 0 || sl.CacheCreationTokens != 0
			if !hasTokens {
				continue
			}

			// Accumulate into per-bead aggregates (keyed by phase_id).
			agg, ok := beads[sl.PhaseID]
			if !ok {
				agg = &beadAgg{beadID: sl.BeadID, tier: sl.Model}
				beads[sl.PhaseID] = agg
			}
			// Token fields accumulate across requeues in the ledger (see
			// ledger.Slot doc); we must NOT double-count here. Each slot in a
			// run represents the cumulative total for that bead in that run —
			// so we replace (not add) when we see the same phaseID again in a
			// later run, since the later run's slot already carries the full
			// cumulative spend.
			agg.in = sl.InputTokens
			agg.out = sl.OutputTokens
			agg.cr = sl.CacheReadTokens
			agg.cc = sl.CacheCreationTokens
			if sl.Model != "" {
				agg.tier = sl.Model
			}
			if sl.BeadID != "" {
				agg.beadID = sl.BeadID
			}

			slotTotal := sl.InputTokens + sl.OutputTokens + sl.CacheReadTokens + sl.CacheCreationTokens
			runTotalTokens += slotTotal
			runBeadCount++
		}

		if runBeadCount > 0 {
			mean := runTotalTokens / int64(runBeadCount)
			stat.RunTrend = append(stat.RunTrend, RunTokenSummary{
				RunID:       run.RunID,
				StartedAt:   run.StartedAt,
				Beads:       runBeadCount,
				TotalTokens: runTotalTokens,
				MeanPerBead: mean,
			})
		}
	}

	// Cap trend to 20 most-recent runs (RunTrend is oldest-first; trim front).
	if len(stat.RunTrend) > 20 {
		stat.RunTrend = stat.RunTrend[len(stat.RunTrend)-20:]
	}

	// Build Beads list and tier aggregates from the final per-bead state.
	var totalIn, totalOut, totalCR, totalCC int64
	for phaseID, agg := range beads {
		row := BeadTokenRow{
			BeadID:      agg.beadID,
			PhaseID:     phaseID,
			Tier:        agg.tier,
			Composition: makeComposition(agg.in, agg.out, agg.cr, agg.cc),
		}
		stat.Beads = append(stat.Beads, row)

		totalIn += agg.in
		totalOut += agg.out
		totalCR += agg.cr
		totalCC += agg.cc

		// Per-tier accumulation.
		ts := stat.ByTier[agg.tier]
		ts.Tier = agg.tier
		ts.Slots++
		ts.Composition = makeComposition(
			ts.Composition.Input+agg.in,
			ts.Composition.Output+agg.out,
			ts.Composition.CacheRead+agg.cr,
			ts.Composition.CacheCreation+agg.cc,
		)
		stat.ByTier[agg.tier] = ts
	}

	// Finalise tier mean-per-slot.
	for k, ts := range stat.ByTier {
		if ts.Slots > 0 {
			ts.MeanPerSlot = ts.Composition.Total / int64(ts.Slots)
		}
		stat.ByTier[k] = ts
	}

	stat.Composition = makeComposition(totalIn, totalOut, totalCR, totalCC)
	stat.TotalBeads = len(beads)
	if stat.TotalBeads > 0 {
		stat.MeanPerBead = stat.Composition.Total / int64(stat.TotalBeads)
	}

	// Sort beads by total tokens descending for the human table.
	sort.Slice(stat.Beads, func(i, j int) bool {
		return stat.Beads[i].Composition.Total > stat.Beads[j].Composition.Total
	})

	return stat
}

// RenderTokens writes an aligned per-project token table to w.
// For machine-readable output use --json (cmdMetricsTokens).
func RenderTokens(r *TokenReport, w io.Writer) {
	if r == nil || len(r.Projects) == 0 {
		fmt.Fprintln(w, "no token data yet (dispatches with token fields accumulate it automatically)")
		return
	}

	for _, p := range r.Projects {
		fmt.Fprintf(w, "project: %s  account: %s\n", p.ProjectID, p.Account)
		fmt.Fprintf(w, "  total beads: %d  mean tokens/bead: %s  cache-hit: %.1f%%\n",
			p.TotalBeads, fmtTokens(p.MeanPerBead), p.Composition.CacheHitRatio*100)
		fmt.Fprintf(w, "  composition: input=%s  output=%s  cache_read=%s  cache_creation=%s  total=%s\n\n",
			fmtTokens(p.Composition.Input),
			fmtTokens(p.Composition.Output),
			fmtTokens(p.Composition.CacheRead),
			fmtTokens(p.Composition.CacheCreation),
			fmtTokens(p.Composition.Total),
		)

		if len(p.ByTier) > 0 {
			tw := tabwriter.NewWriter(w, 0, 0, 2, ' ', 0)
			fmt.Fprintln(tw, "  TIER\tSLOTS\tINPUT\tOUTPUT\tCACHE_READ\tCACHE_CREATE\tTOTAL\tCACHE_HIT\tMEAN/SLOT")
			for _, tier := range sortedTierKeys(p.ByTier) {
				ts := p.ByTier[tier]
				label := tier
				if label == "" {
					label = "-"
				}
				fmt.Fprintf(tw, "  %s\t%d\t%s\t%s\t%s\t%s\t%s\t%.1f%%\t%s\n",
					label, ts.Slots,
					fmtTokens(ts.Composition.Input),
					fmtTokens(ts.Composition.Output),
					fmtTokens(ts.Composition.CacheRead),
					fmtTokens(ts.Composition.CacheCreation),
					fmtTokens(ts.Composition.Total),
					ts.Composition.CacheHitRatio*100,
					fmtTokens(ts.MeanPerSlot),
				)
			}
			tw.Flush()
			fmt.Fprintln(w)
		}

		if len(p.Beads) > 0 {
			// Show top beads (up to 20).
			limit := len(p.Beads)
			if limit > 20 {
				limit = 20
			}
			bw := tabwriter.NewWriter(w, 0, 0, 2, ' ', 0)
			fmt.Fprintln(bw, "  BEAD/PHASE\tTIER\tINPUT\tOUTPUT\tCACHE_READ\tCACHE_CREATE\tTOTAL\tCACHE_HIT")
			for i := 0; i < limit; i++ {
				b := p.Beads[i]
				id := b.PhaseID
				if b.BeadID != "" {
					id = b.BeadID
				}
				tier := b.Tier
				if tier == "" {
					tier = "-"
				}
				fmt.Fprintf(bw, "  %s\t%s\t%s\t%s\t%s\t%s\t%s\t%.1f%%\n",
					id, tier,
					fmtTokens(b.Composition.Input),
					fmtTokens(b.Composition.Output),
					fmtTokens(b.Composition.CacheRead),
					fmtTokens(b.Composition.CacheCreation),
					fmtTokens(b.Composition.Total),
					b.Composition.CacheHitRatio*100,
				)
			}
			bw.Flush()
			if len(p.Beads) > 20 {
				fmt.Fprintf(w, "  ... and %d more beads (use --json for full list)\n", len(p.Beads)-20)
			}
			fmt.Fprintln(w)
		}

		if len(p.RunTrend) > 0 {
			fmt.Fprintln(w, "  tokens/bead trend (oldest → newest):")
			tw := tabwriter.NewWriter(w, 0, 0, 2, ' ', 0)
			fmt.Fprintln(tw, "    RUN\tBEADS\tTOTAL\tMEAN/BEAD")
			for _, rt := range p.RunTrend {
				fmt.Fprintf(tw, "    %s\t%d\t%s\t%s\n",
					rt.RunID, rt.Beads,
					fmtTokens(rt.TotalTokens),
					fmtTokens(rt.MeanPerBead),
				)
			}
			tw.Flush()
			fmt.Fprintln(w)
		}
	}
}

// fmtTokens formats a token count as a human-readable string (e.g. "1.2M",
// "340K", "812").
func fmtTokens(n int64) string {
	switch {
	case n >= 1_000_000:
		return fmt.Sprintf("%.1fM", float64(n)/1_000_000)
	case n >= 1_000:
		return fmt.Sprintf("%.1fK", float64(n)/1_000)
	default:
		return fmt.Sprintf("%d", n)
	}
}

// sortedTierKeys returns tier keys of m in stable order.
func sortedTierKeys(m map[string]TierTokenStat) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
